# Uncomment this line to define a global platform for your project
  

platform :ios, '8.0'
target 'QQA' do
 
    pod 'AFNetworking', '~> 3.0'
    pod 'MJRefresh'
    pod ‘SDCycleScrollView‘,‘~> 1.6‘
       
end
